---
- import_tasks: virtualenv.yaml

# required for configuring jupyterlab
- name: Install dev tools
  yum:
    name: "@Development Tools"
    state: present

# https://stackoverflow.com/a/51002197
- name: Install previous version of tornado in system virtualenv
  pip:
    virtualenv: "{{ jupyterlab_venv }}"
    umask: "022"
    name: tornado
    state: present
    version: 4.5.3
  when:
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution_major_version == '6'"

- name: Install jupyterlab in the system virtualenv
  pip:
    virtualenv: "{{ jupyterlab_venv }}"
    umask: "022"
    name: jupyterlab
    state: present

- name: Create a desktop entry for launching JupyterLab
  template:
    src: jupyterlab.desktop
    dest: /usr/share/applications/jupyterlab.desktop
    owner: root
    group: root
    mode: 0644
