---
- import_tasks: virtualenv.yaml

# required for installing python extensions
- name: Install dev tools
  yum:
    name: "@Development Tools"
    state: present

# https://stackoverflow.com/a/51002197
- name: Install previous version of tornado in system virtualenv
  pip:
    virtualenv: "{{ jupyter_venv }}"
    umask: "022"
    name: tornado
    state: present
    version: 4.5.3
  when:
    - "ansible_os_family == 'RedHat'"
    - "ansible_distribution_major_version == '6'"

- name: Install python packages in the virtualenv
  pip:
    virtualenv: "{{ jupyter_venv }}"
    umask: "022"
    name: "{{ item }}"
    state: present
  with_items:
    - jupyter
    - jupyterlab

- name: Create a desktop entries
  template:
    src: "{{ item }}.desktop"
    dest: "/usr/share/applications/{{ item }}.desktop"
    owner: root
    group: root
    mode: 0644
  with_items:
    - jupyter
    - jupyterlab
