---
- name: Create virtual env
  shell: "umask 022; virtualenv -p {{ jupyter_python }} {{ jupyter_venv }}"
  args:
    creates: "{{ jupyter_venv }}"

- name: Update pip
  pip:
    umask: "022"
    virtualenv: "{{ jupyter_venv }}"
    name: pip
    state: latest

# We had RHEL-06-000282 (There must be no world-writable files on the system.)
# trip on us.  I think it was setuptools.  Permission hammer it.
- name: Clean up dumb permissions
  file:
    dest: "{{ jupyter_venv }}"
    state: directory
    recurse: True
    mode: "o-w" # duh?
